### ISSUE TITLE
tensors must have same number of dimensions: got 2 and 3 

### ISSUE THREAD

**Issue by Ella77** [albertpumarola/GANimation#110]
I encountered dimension error after finishing epoch 1. 

[02/12/2019 03:42:48] (Tv, epoch: 1, it: 373/2194, t/smpl: 0.031s) g_fake:0.000 g_cond:0.000 g_mskd_fake:-0.087 g_mskd_cond:2.259 g_cyc:0.014 g_rgb:0.000 g_rgb_un:0.000 g_rgb_s:0.000 g_m1:0.100 g_m2:0.100 g_m1_s:0.002 g_m2_s:0.002 g_idt:0.000 d_real:-0.085 d_cond:1.036 d_fake:0.084 d_gp:0.090
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    Train()
  File "train.py", line 27, in __init__
    self._train()
  File "train.py", line 40, in _train
    self._train_epoch(i_epoch)
  File "train.py", line 59, in _train_epoch
    for i_train_batch, train_batch in enumerate(self._dataset_train):
  File "/home/soojin/.conda/envs/soojin/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/soojin/.conda/envs/soojin/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/soojin/.conda/envs/soojin/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/soojin/.conda/envs/soojin/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 63, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/home/soojin/.conda/envs/soojin/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 63, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/home/soojin/.conda/envs/soojin/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 52, in default_collate
    return default_collate([torch.from_numpy(b) for b in batch])
  File "/home/soojin/.conda/envs/soojin/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 43, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Tensors must have same number of dimensions: got 2 and 3 at /opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/TH/generic/THTensor.cpp:702

**Comment by LuchenCatherine** [comment]
I encountered this problem, too. Have you solved it?
