### ISSUE TITLE
some questions about the code

### ISSUE THREAD

**Issue by xskyz** [albertpumarola/GANimation#13]
hello,when I run the code( train.py ) with your sample_dataset,I run this order
"python train.py \
--data_dir sample_dataset/ \
--name experiment_1 \
--batch_size 2 \  "

 I get this error message:

Traceback (most recent call last):
  File "/home/xsky/projects/GANimation-master/train.py", line 142, in <module>
    Train()
  File "/home/xsky/projects/GANimation-master/train.py", line 14, in __init__
    data_loader_test = CustomDatasetDataLoader(self._opt, is_for_train=False)
  File "/home/xsky/projects/GANimation-master/data/custom_dataset_data_loader.py", line 10, in __init__
    self._create_dataset()
  File "/home/xsky/projects/GANimation-master/data/custom_dataset_data_loader.py", line 13, in _create_dataset
    self._dataset = DatasetFactory.get_by_name(self._opt.dataset_mode, self._opt, self._is_for_train)
  File "/home/xsky/projects/GANimation-master/data/dataset.py", line 16, in get_by_name
    dataset = AusDataset(opt, is_for_train)
  File "/home/xsky/projects/GANimation-master/data/dataset_aus.py", line 17, in __init__
    self._read_dataset_paths()
  File "/home/xsky/projects/GANimation-master/data/dataset_aus.py", line 68, in _read_dataset_paths
    self._ids = self._read_ids(use_ids_filepath)
  File "/home/xsky/projects/GANimation-master/data/dataset_aus.py", line 96, in _read_ids
    return [id[:-4] for id in ids]
TypeError: iteration over a 0-d array

I don't know where the problem is，so, would you please answer it?Thank you very much!

**Comment by zoey9594** [comment]
I have also appeared this problem, I hope that my solution can be successful.
The problem is on numpy.
Need to be in /data/dataset_aus.py
Def _read_ids(self, file_path):
         Ids = np.loadtxt(file_path, delimiter='\t', dtype=np.str) #Make this change
         Return [id[:-4] for id in ids]
——>
Ids = np.loadtxt(list(file_path), delimiter='\t', dtype=np.str)

**Comment by albertpumarola** [comment]
The code was implemented for a large dataset, only having one test sample cause this error, I have added an extra sample. pull and try again, it should be solved.
