### ISSUE TITLE
 Sizes of tensors must match except in dimension 0.

### ISSUE THREAD

**Issue by voa18105** [albertpumarola/GANimation#17]
I have an error when I launch training, it says:

Network generator_wasserstein_gan was created
Network discriminator_wasserstein_gan was created
Model GANimation was created
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    Train()
  File "train.py", line 27, in __init__
    self._train()
  File "train.py", line 40, in _train
    self._train_epoch(i_epoch)
  File "train.py", line 59, in _train_epoch
    for i_train_batch, train_batch in enumerate(self._dataset_train):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 184, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 184, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 164, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 558 and 357 in dimension 2 at /pytorch/aten/src/TH/generic/THTensorMath.cpp:3616

These two numbers (558 and 357) are different with each launching. Do you have any ideas how to fix it?

**Comment by albertpumarola** [comment]
Looks like you are training with images of different sizes, PyTorch does not support it by default.

**Comment by hfengzhi** [comment]
i meet the same error .could you recommend a suitable database? i  had readlly try a lot.

**Comment by voa18105** [comment]
@hfengzhi i suppose any dataset is fine, but you have to crop faces and resize them to 128x128
