### ISSUE TITLE
 RuntimeError: Error(s) in loading state_dict for Generator:

### ISSUE THREAD

**Issue by voa18105** [albertpumarola/GANimation#19]
I've trained a model and experiencing problems to path an image through it. It says:

------------ Options -------------
aus_file: aus_openface.pkl
batch_size: 4
checkpoints_dir: ./checkpoints
cond_nc: 17
data_dir: None
dataset_mode: aus
do_saturate_mask: False
gpu_ids: [0]
image_size: 128
images_folder: imgs
input_path: ./sample_dataset/imgs/N_0000001507_00202.jpg
is_train: False
load_epoch: 30
model: ganimation
n_threads_test: 1
name: experiment_1
output_dir: ./output
serial_batches: False
test_ids_file: test_ids.csv
train_ids_file: train_ids.csv
-------------- End ----------------
./checkpoints/experiment_1
Network generator_wasserstein_gan was created
Network discriminator_wasserstein_gan was created
Traceback (most recent call last):
  File "test.py", line 74, in <module>
    main()
  File "test.py", line 65, in main
    morph = MorphFacesInTheWild(opt)
  File "test.py", line 19, in __init__
    self._model = ModelsFactory.get_by_name(self._opt.model, self._opt)
  File "/home/WX466836/docker_mount/GANimation/models/models.py", line 15, in get_by_name
    model = GANimation(*args, **kwargs)
  File "/home/WX466836/docker_mount/GANimation/models/ganimation.py", line 26, in __init__
    self.load()
  File "/home/WX466836/docker_mount/GANimation/models/ganimation.py", line 376, in load
    self._load_network(self._G, 'G', load_epoch)
  File "/home/WX466836/docker_mount/GANimation/models/models.py", line 105, in _load_network
    network.load_state_dict(torch.load(load_path))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Generator:
        Missing key(s) in state_dict: "main.0.weight", "main.1.bias", "main.1.weight", "main.3.weight", "main.4.bias", "main.4.weight", "main.6.weight", "main.7.bias", "main.7.weight", "main.9.main.0.weight", "main.9.main.1.bias", "main.9.main.1.weight", "main.9.main.3.weight", "main.9.main.4.bias", "main.9.main.4.weight", "main.10.main.0.weight", "main.10.main.1.bias", "main.10.main.1.weight", "main.10.main.3.weight", "main.10.main.4.bias", "main.10.main.4.weight", "main.11.main.0.weight", "main.11.main.1.bias", "main.11.main.1.weight", "main.11.main.3.weight", "main.11.main.4.bias", "main.11.main.4.weight", "main.12.main.0.weight", "main.12.main.1.bias", "main.12.main.1.weight", "main.12.main.3.weight", "main.12.main.4.bias", "main.12.main.4.weight", "main.13.main.0.weight", "main.13.main.1.bias", "main.13.main.1.weight", "main.13.main.3.weight", "main.13.main.4.bias", "main.13.main.4.weight", "main.14.main.0.weight", "main.14.main.1.bias", "main.14.main.1.weight", "main.14.main.3.weight", "main.14.main.4.bias", "main.14.main.4.weight", "main.15.weight", "main.16.bias", "main.16.weight", "main.18.weight", "main.19.bias", "main.19.weight", "img_reg.0.weight", "attetion_reg.0.weight".
        Unexpected key(s) in state_dict: "module.main.0.weight", "module.main.1.weight", "module.main.1.bias", "module.main.3.weight", "module.main.4.weight", "module.main.4.bias", "module.main.6.weight", "module.main.7.weight", "module.main.7.bias", "module.main.9.main.0.weight", "module.main.9.main.1.weight", "module.main.9.main.1.bias", "module.main.9.main.3.weight", "module.main.9.main.4.weight", "module.main.9.main.4.bias", "module.main.10.main.0.weight", "module.main.10.main.1.weight", "module.main.10.main.1.bias", "module.main.10.main.3.weight", "module.main.10.main.4.weight", "module.main.10.main.4.bias", "module.main.11.main.0.weight", "module.main.11.main.1.weight", "module.main.11.main.1.bias", "module.main.11.main.3.weight", "module.main.11.main.4.weight", "module.main.11.main.4.bias", "module.main.12.main.0.weight", "module.main.12.main.1.weight", "module.main.12.main.1.bias", "module.main.12.main.3.weight", "module.main.12.main.4.weight", "module.main.12.main.4.bias", "module.main.13.main.0.weight", "module.main.13.main.1.weight", "module.main.13.main.1.bias", "module.main.13.main.3.weight", "module.main.13.main.4.weight", "module.main.13.main.4.bias", "module.main.14.main.0.weight", "module.main.14.main.1.weight", "module.main.14.main.1.bias", "module.main.14.main.3.weight", "module.main.14.main.4.weight", "module.main.14.main.4.bias", "module.main.15.weight", "module.main.16.weight", "module.main.16.bias", "module.main.18.weight", "module.main.19.weight", "module.main.19.bias", "module.img_reg.0.weight", "module.attetion_reg.0.weight".

Do you have any advice to make it work?

**Comment by voa18105** [comment]
I understand that the problem is with weights names, i can rename it... i just do not understand why does this happen? isn't it standard save/load functions?

**Comment by voa18105** [comment]
I've solved the problem and actually got first result, still it is not clear why this happened.
