### ISSUE TITLE
 Zero-sized dimensions are not supported in PyTorch

### ISSUE THREAD

**Issue by xiaoiker** [albertpumarola/GANimation#28]
saving the latest model (epoch 3, total_steps 375825)
saved net: ./checkpoints/experiment_1/net_epoch_3_id_G.pth
saved net: ./checkpoints/experiment_1/net_epoch_3_id_D.pth
[27/08/2018 18:08:54] (T, epoch: 3, it: 121/7516, t/smpl: 0.017s) g_fake:0.000 g_cond:0.000 g_mskd_fake:-0.242 g_mskd_cond:3.193 g_cyc:1.215 g_rgb:0.000 g_rgb_un:0.000 g_rgb_s:0.000 g_m1:0.067 g_m2:0.067 g_m1_s:0.134 g_m2_s:0.129 g_idt:0.000 d_real:-0.856 d_cond:2.661 d_fake:0.491 d_gp:0.107
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    Train()
  File "train.py", line 27, in __init__
    self._train()
  File "train.py", line 40, in _train
    self._train_epoch(i_epoch)
  File "train.py", line 59, in _train_epoch
    for i_train_batch, train_batch in enumerate(self._dataset_train):
  File "/appl/opt/python/mlpython-2.7.10/site-packages/torch/utils/data/dataloader.py", line 210, in __next__
    return self._process_next_batch(batch)
  File "/appl/opt/python/mlpython-2.7.10/site-packages/torch/utils/data/dataloader.py", line 230, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/appl/opt/python/mlpython-2.7.10/site-packages/torch/utils/data/dataloader.py", line 42, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/appl/opt/python/mlpython-2.7.10/site-packages/torch/utils/data/dataloader.py", line 116, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/appl/opt/python/mlpython-2.7.10/site-packages/torch/utils/data/dataloader.py", line 116, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/appl/opt/python/mlpython-2.7.10/site-packages/torch/utils/data/dataloader.py", line 105, in default_collate
    return torch.stack([torch.from_numpy(b) for b in batch], 0)
RuntimeError: the given numpy array has zero-sized dimensions. Zero-sized dimensions are not supported in PyTorch

Hello, I get an error like this. Can you give me some suggestions? Maybe the pytorch version is not right?

**Comment by albertpumarola** [comment]
Seems there is something wrong with your dataset. Check that the dimensions of each element of a sample are always the same.

**Comment by BugTan** [comment]
when the test sample size is 1, python will raise this error, you can add a special treat where there is only one test or train samples

**Comment by xiaoiker** [comment]
I checked our my images with the following code, found no zero size image. There are around 200K imgs.

	input_path ='/homeappl/home/imgs'
	files = glob.glob(input_path+'*.j*')
	for n, img in enumerate(files):# /*.*
		try:
			var_img = cv2.imread(img) 
			height, weight, C = var_img.shape
			if (height != 128)|(weight != 128)|(C != 3):
				os.remove(img)
				print('Deleting file: {}'.format(img))
			else if var_img is None:
				os.remove(img)
				print('Deleting file: {}'.format(img))				

			print(n)
		
		except:
			os.remove(img)
			print('Deleting file: {}'.format(img))

I also checked the AUs files, found no abnormal. But still not work.

**Comment by huahuachenchen** [comment]
@xiaoiker when load data in dataset_au.py, real_cond or desired_cond  may have zero-sized dimensions, you can  add a special treat, and I meet this problem and now success to train.

**Comment by yangzhikai** [comment]
@xiaoiker   I have  try the way proposed by  (AidasK commented on 4 Sep),and This method is also applicable to the Celeba Dataset.
