### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by BugTan** [albertpumarola/GANimation#34]
I use a single GTX 1080TI which is the same as the author,but it raise cuda out of  memeory. why?
(dl) root@63c12776c653:/data/GANimataion# bash launch/run_train.sh
------------ Options -------------
D_adam_b1: 0.5
D_adam_b2: 0.999
G_adam_b1: 0.5
G_adam_b2: 0.999
aus_file: aus_openface.pkl
batch_size: 25
checkpoints_dir: ./checkpoints
cond_nc: 17
data_dir: /input
dataset_mode: aus
display_freq_s: 300
do_saturate_mask: False
gpu_ids: [0]
image_size: 128
images_folder: imgs
is_train: True
lambda_D_cond: 4000
lambda_D_gp: 10
lambda_D_prob: 1
lambda_cyc: 10
lambda_mask: 0.1
lambda_mask_smooth: 1e-05
load_epoch: 0
lr_D: 0.0001
lr_G: 0.0001
model: ganimation
n_threads_test: 1
n_threads_train: 1
name: experiment_ck
nepochs_decay: 10
nepochs_no_decay: 20
num_iters_validate: 1
poses_g_sigma: 0.06
print_freq_s: 60
save_latest_freq_s: 3600
serial_batches: False
test_ids_file: test_ids.csv
train_G_every_n_iterations: 5
train_ids_file: train_ids.csv
-------------- End ----------------
./checkpoints/experiment_ck
Dataset AusDataset was created
Dataset AusDataset was created
#train images = 8791
#test images = 4
Network generator_wasserstein_gan was created
Network discriminator_wasserstein_gan was created
Model GANimation was created
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    Train()
  File "train.py", line 27, in __init__
    self._train()
  File "train.py", line 40, in _train
    self._train_epoch(i_epoch)
  File "train.py", line 69, in _train_epoch
    self._model.optimize_parameters(keep_data_for_visuals=do_visuals, train_generator=train_generator)
  File "/data/GANimataion/models/ganimation.py", line 207, in optimize_parameters
    loss_D, fake_imgs_masked = self._forward_D()
  File "/data/GANimataion/models/ganimation.py", line 273, in _forward_D
    fake_imgs, fake_img_mask = self._G.forward(self._real_img, self._desired_cond)
  File "/data/GANimataion/networks/generator_wasserstein_gan.py", line 53, in forward
    features = self.main(x)
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/GANimataion/networks/generator_wasserstein_gan.py", line 68, in forward
    return x + self.main(x)
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: out of memory
(dl) root@63c12776c653:/data/GANimataion# bash launch/run_train.sh
------------ Options -------------
D_adam_b1: 0.5
D_adam_b2: 0.999
G_adam_b1: 0.5
G_adam_b2: 0.999
aus_file: aus_openface.pkl
batch_size: 25
checkpoints_dir: ./checkpoints
cond_nc: 17
data_dir: /input
dataset_mode: aus
display_freq_s: 300
do_saturate_mask: False
gpu_ids: [0]
image_size: 128
images_folder: imgs
is_train: True
lambda_D_cond: 4000
lambda_D_gp: 10
lambda_D_prob: 1
lambda_cyc: 10
lambda_mask: 0.1
lambda_mask_smooth: 1e-05
load_epoch: 0
lr_D: 0.0001
lr_G: 0.0001
model: ganimation
n_threads_test: 1
n_threads_train: 1
name: experiment_ck
nepochs_decay: 10
nepochs_no_decay: 20
num_iters_validate: 1
poses_g_sigma: 0.06
print_freq_s: 60
save_latest_freq_s: 3600
serial_batches: False
test_ids_file: test_ids.csv
train_G_every_n_iterations: 5
train_ids_file: train_ids.csv
-------------- End ----------------
./checkpoints/experiment_ck
Dataset AusDataset was created
Dataset AusDataset was created
#train images = 8791
#test images = 4
Network generator_wasserstein_gan was created
Network discriminator_wasserstein_gan was created
Model GANimation was created
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    Train()
  File "train.py", line 27, in __init__
    self._train()
  File "train.py", line 40, in _train
    self._train_epoch(i_epoch)
  File "train.py", line 69, in _train_epoch
    self._model.optimize_parameters(keep_data_for_visuals=do_visuals, train_generator=train_generator)
  File "/data/GANimataion/models/ganimation.py", line 207, in optimize_parameters
    loss_D, fake_imgs_masked = self._forward_D()
  File "/data/GANimataion/models/ganimation.py", line 273, in _forward_D
    fake_imgs, fake_img_mask = self._G.forward(self._real_img, self._desired_cond)
  File "/data/GANimataion/networks/generator_wasserstein_gan.py", line 53, in forward
    features = self.main(x)
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/GANimataion/networks/generator_wasserstein_gan.py", line 68, in forward
    return x + self.main(x)
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: out of memory

**Comment by albertpumarola** [comment]
Try decreasing your batch size.
