### ISSUE TITLE
anyone help?

### ISSUE THREAD

**Issue by jackylee1** [albertpumarola/GANimation#52]
python train.py  --data_dir mydata2 --name experiment_1 --batch_size 25

------------ Options -------------
D_adam_b1: 0.5
D_adam_b2: 0.999
G_adam_b1: 0.5
G_adam_b2: 0.999
aus_file: aus_openface.pkl
batch_size: 25
checkpoints_dir: ./checkpoints
cond_nc: 17
data_dir: mydata2
dataset_mode: aus
display_freq_s: 300
do_saturate_mask: False
gpu_ids: [0]
image_size: 128
images_folder: imgs
is_train: True
lambda_D_cond: 4000
lambda_D_gp: 10
lambda_D_prob: 1
lambda_cyc: 10
lambda_mask: 0.1
lambda_mask_smooth: 1e-05
load_epoch: 0
lr_D: 0.0001
lr_G: 0.0001
model: ganimation
n_threads_test: 1
n_threads_train: 4
name: experiment_1
nepochs_decay: 10
nepochs_no_decay: 20
num_iters_validate: 1
poses_g_sigma: 0.06
print_freq_s: 60
save_latest_freq_s: 3600
serial_batches: False
test_ids_file: test_ids.csv
train_G_every_n_iterations: 5
train_ids_file: train_ids.csv
-------------- End ----------------
./checkpoints/experiment_1
Dataset AusDataset was created
Dataset AusDataset was created
#train images = 202056
#test images = 202056
Network generator_wasserstein_gan was created
Network discriminator_wasserstein_gan was created
Model GANimation was created
/data/GANimation/models/ganimation.py:320: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  ('g_mskd_fake', self._loss_g_masked_fake.data[0]),
/data/GANimation/models/ganimation.py:321: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  ('g_mskd_cond', self._loss_g_masked_cond.data[0]),
/data/GANimation/models/ganimation.py:322: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  ('g_cyc', self._loss_g_cyc.data[0]),
/data/GANimation/models/ganimation.py:326: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  ('g_m1', self._loss_g_mask_1.data[0]),
/data/GANimation/models/ganimation.py:327: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  ('g_m2', self._loss_g_mask_2.data[0]),
/data/GANimation/models/ganimation.py:328: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  ('g_m1_s', self._loss_g_mask_1_smooth.data[0]),
/data/GANimation/models/ganimation.py:329: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  ('g_m2_s', self._loss_g_mask_2_smooth.data[0]),
/data/GANimation/models/ganimation.py:331: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  ('d_real', self._loss_d_real.data[0]),
/data/GANimation/models/ganimation.py:332: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  ('d_cond', self._loss_d_cond.data[0]),
/data/GANimation/models/ganimation.py:333: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  ('d_fake', self._loss_d_fake.data[0]),
/data/GANimation/models/ganimation.py:334: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  ('d_gp', self._loss_d_gp.data[0])])
[18/10/2018 18:24:40] (Tv, epoch: 1, it: 0/8082, t/smpl: 0.049s) g_fake:0.000 g_cond:0.000 g_mskd_fake:-0.028 g_mskd_cond:15517.005 g_cyc:3.964 g_rgb:0.000 g_rgb_un:0.000 g_rgb_s:0.000 g_m1:0.057 g_m2:0.057 g_m1_s:0.764 g_m2_s:0.755 g_idt:0.000 d_real:-0.026 d_cond:16090.376 d_fake:0.013 d_gp:7.328
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/util.py", line 274, in _run_finalizers
    finalizer()
  File "/usr/lib/python2.7/multiprocessing/util.py", line 207, in __call__
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/util.py", line 274, in _run_finalizers
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/shutil.py", line 252, in rmtree
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/util.py", line 274, in _run_finalizers
    finalizer()
  File "/usr/lib/python2.7/multiprocessing/util.py", line 207, in __call__
    onerror(os.remove, fullname, sys.exc_info())
Traceback (most recent call last):
  File "/usr/lib/python2.7/shutil.py", line 250, in rmtree
  File "/usr/lib/python2.7/multiprocessing/util.py", line 274, in _run_finalizers
    os.remove(fullname)
    res = self._callback(*self._args, **self._kwargs)
OSError: [Errno 16] Device or resource busy: '/tmp/pymp-XanIEN/.nfs00000000087e0d9300004faf'
  File "/usr/lib/python2.7/shutil.py", line 252, in rmtree
    finalizer()
  File "/usr/lib/python2.7/multiprocessing/util.py", line 207, in __call__
    finalizer()
    res = self._callback(*self._args, **self._kwargs)
    onerror(os.remove, fullname, sys.exc_info())
  File "/usr/lib/python2.7/multiprocessing/util.py", line 207, in __call__
  File "/usr/lib/python2.7/shutil.py", line 252, in rmtree
  File "/usr/lib/python2.7/shutil.py", line 250, in rmtree
    res = self._callback(*self._args, **self._kwargs)
    os.remove(fullname)
  File "/usr/lib/python2.7/shutil.py", line 252, in rmtree
OSError: [Errno 16] Device or resource busy: '/tmp/pymp-w9YT_u/.nfs00000000087e0d8f00004fb1'
    onerror(os.remove, fullname, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 16] Device or resource busy: '/tmp/pymp-VtcW1b/.nfs00000000087e0d9100004fb2'
    onerror(os.remove, fullname, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 16] Device or resource busy: '/tmp/pymp-DjMpR_/.nfs00000000087e0d9500004fb0'
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    Train()
  File "train.py", line 27, in __init__
    self._train()
  File "train.py", line 40, in _train
    self._train_epoch(i_epoch)
  File "train.py", line 82, in _train_epoch
    self._display_visualizer_train(self._total_steps)
  File "train.py", line 98, in _display_visualizer_train
    self._tb_visualizer.display_current_results(self._model.get_current_visuals(), total_steps, is_train=True)
  File "/data/GANimation/models/ganimation.py", line 347, in get_current_visuals
    visuals['1_input_img'] = plot_utils.plot_au(self._vis_real_img, self._vis_real_cond, title=title_input_img)
  File "/data/GANimation/utils/plots.py", line 14, in plot_au
    fig = plt.figure()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/_backend_tk.py", line 1046, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1818, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

is that something wrong with my data?

**Comment by jackylee1** [comment]
and now it shows 
raise TypeError("Cannot handle this data type")
TypeError: Cannot handle this data type

**Comment by albertpumarola** [comment]
Seems this is a versions error. You are probably using Pytorch 0.4, this code was made previous to this version release. It was made for Pytorch 0.3.1.

**Comment by albertpumarola** [comment]
Check issue #49
