### ISSUE TITLE
error reading images

### ISSUE THREAD

**Issue by ZHUTAO142857** [albertpumarola/GANimation#59]
I use 22K images from EmotioNet to train the model. However, some error comes up.
------------------------------------------------------------------------
./checkpoints/experiment_1
Dataset AusDataset was created
Dataset AusDataset was created
#train images = 175436
#test images = 48414
Network generator_wasserstein_gan was created
Network discriminator_wasserstein_gan was created
Model GANimation was created
error reading image N_0000000315_00913, skipping sample
error reading image N_0000000438_00773, skipping sample
error reading image N_0000000225_00354, skipping sample
error reading image N_0000000534_00443, skipping sample
error reading image N_0000000410_00453, skipping sample
error reading image N_0000000287_00339, skipping sample
error reading image N_0000000471_00078, skipping sample
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    Train()
  File "train.py", line 27, in __init__
    self._train()
  File "train.py", line 40, in _train
    self._train_epoch(i_epoch)
  File "train.py", line 59, in _train_epoch
    for i_train_batch, train_batch in enumerate(self._dataset_train):
  File "/home/zhutao/anaconda3/envs/ganimation/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/zhutao/anaconda3/envs/ganimation/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/zhutao/anaconda3/envs/ganimation/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/zhutao/anaconda3/envs/ganimation/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 184, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/home/zhutao/anaconda3/envs/ganimation/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 184, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/home/zhutao/anaconda3/envs/ganimation/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 173, in default_collate
    return torch.stack([torch.from_numpy(b) for b in batch], 0)
RuntimeError: cannot unsqueeze empty tensor

error reading image N_0000000570_00513, skipping sample
error reading image N_0000000406_00513, skipping sample

**Comment by ZHUTAO142857** [comment]
I've read the issues before which does not works for me, so I write an issue again

**Comment by albertpumarola** [comment]
This error is produced when the image is not found in the provided dataset path. Make sure to check that the images are in the directory you have provided and pull for possible code updates.

**Comment by ZHUTAO142857** [comment]
> This error is produced when the image is not found in the provided dataset path. Make sure to check that the images are in the directory you have provided and pull for possible code updates.

I am not sure but I can find the error reading images in the provided path. And it is strange that the error reading images are gray images.

**Comment by albertpumarola** [comment]
The code is only prepared to handle RGB images.
