### ISSUE TITLE
Testing problem

### ISSUE THREAD

**Issue by litterzq** [albertpumarola/GANimation#98]
The model has been trained, and the following problems appeared in the final test. How can I solve them?
------------------------------------------------------------------------------------------------------------------------
------------ Options -------------
aus_file: aus_openface.pkl
batch_size: 4
checkpoints_dir: ./checkpoints
cond_nc: 17
data_dir: None
dataset_mode: aus
do_saturate_mask: False
gpu_ids: [0]
image_size: 128
images_folder: imgs
input_path: /media/zhangqi/8ACA684CCA68369B/tensorflow/GANimation-maste/img
is_train: False
load_epoch: 30
model: ganimation
n_threads_test: 1
name: experiment_1
output_dir: ./output
serial_batches: False
test_ids_file: test_ids.csv
train_ids_file: train_ids.csv
-------------- End ----------------
./checkpoints/experiment_1
Network generator_wasserstein_gan was created
Network discriminator_wasserstein_gan was created
loaded net: ./checkpoints/experiment_1/net_epoch_30_id_G.pth
Model GANimation was created
Traceback (most recent call last):
  File "test.py", line 74, in <module>
    main()
  File "test.py", line 69, in main
    morph.morph_file(image_path, expression)
  File "test.py", line 28, in morph_file
    morphed_img = self._img_morph(img, expresion)
  File "test.py", line 33, in _img_morph
    bbs = face_recognition.face_locations(img)
  File "/home/zhangqi/anaconda3/envs/torch/lib/python3.6/site-packages/face_recognition/api.py", line 118, in face_locations
    return [_trim_css_to_bounds(_rect_to_css(face), img.shape) for face in _raw_face_locations(img, number_of_times_to_upsample, model)]
  File "/home/zhangqi/anaconda3/envs/torch/lib/python3.6/site-packages/face_recognition/api.py", line 102, in _raw_face_locations
    return face_detector(img, number_of_times_to_upsample)
TypeError: __call__(): incompatible function arguments. The following argument types are supported:
    1. (self: dlib.fhog_object_detector, image: array, upsample_num_times: int=0) -> dlib.rectangles

Invoked with: <dlib.fhog_object_detector object at 0x7fcbaf7b1180>, None, 1

**Comment by LinglanZhao** [comment]
Same problem. Have you solved it yet?

**Comment by Daviswww** [comment]
Your input path is "/media/zhangqi/8ACA684CCA68369B/tensorflow/GANimation-maste/img".
You didn't choose the picture,  try to  "python test.py --input_path ./sample_dataset/imgs/N_0000000437_00540.jpg" the output img is in ./output.
