### ISSUE TITLE
Training problem

### ISSUE THREAD

**Issue by longjia1996** [albertpumarola/GANimation#99]
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    Train()
  File "train.py", line 27, in __init__
    self._train()
  File "train.py", line 40, in _train
    self._train_epoch(i_epoch)
  File "train.py", line 69, in _train_epoch
    self._model.optimize_parameters(keep_data_for_visuals=do_visuals, train_generator=train_generator)
  File "/home/longjia/GANimation-master/models/ganimation.py", line 207, in optimize_parameters
    loss_D, fake_imgs_masked = self._forward_D()
  File "/home/longjia/GANimation-master/models/ganimation.py", line 273, in _forward_D
    fake_imgs, fake_img_mask = self._G.forward(self._real_img, self._desired_cond)
  File "/home/longjia/GANimation-master/networks/generator_wasserstein_gan.py", line 51, in forward
    c = c.expand(c.size(0), c.size(1), x.size(2), x.size(3))
RuntimeError: expand(torch.cuda.FloatTensor{[1, 0, 1, 1, 37]}, size=[1, 0, 128, 128]): the number of sizes provided (4) must be greater or equal to the number of dimensions in the tensor (5)

**Comment by xrtbuaa** [comment]
@longjia1996 
I have meet this before  , maybe you can check the format of AU that you provide

**Comment by shartoo** [comment]
batch size should be 25?

**Comment by tjzjp** [comment]
I met the same problem, have you solved it?

**Comment by czwbbbbb** [comment]
> 我以前遇到过这个，也许你可以检查一下你提供的AU格式

hello！I also encountered this problem, I want to ask how this is solved, thank you for your help, that is, this c is 0 channel, can not do concat
